version: "3.3"

services:
  web:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./:/app

  mysqldb:
    image: mysql
    ports:
      - 443:443
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
